### ISSUE TITLE
hashtags with _ and - are not allowed

### ISSUE THREAD

**Issue by matkoniecz** [beeminder/road#90] opened 2019-11-05 07:42 UTC
related to #89

I used #test vs #t_st vs #t-st in Android app to confirm that the problem is real. Only the first was displayed.

Though it may be deliberate - see "Improvements to hashtag parsing: allow uppercase, only count space-separated hashtags "

But for space separated hashtags only the first word is shown, so I am confused - is it intentional that multiword hashtags are impossible?

**Comment by dreeves** [comment] 2019-11-05 18:46
Yeah, I wanted to be quite restrictive about what's parsed as a hashtag to prevent false positives, like "we're #1!" or "called the doctor on their cell#" or any other crazy way someone might end up with a "#" in their comment but not actually intend for it to show up as a hashtag.

I'm interested in a use case where it's not as nice to find a single-word (maybe camelCased?) hashtag!

**Comment by matkoniecz** [comment] 2019-11-06 17:16
I have goal "invited people for cycling". I log cases when I succeeded and went on a trip with someone as 0 point datapoints, with hashtag indicating who went with me. For example `#jan` after cycling with Jan. In this case I added hashtag about cycling with two people `#jan_and_ania` after I went cycling with Jan and Ania. (to be more specific, it was `#jan_i_ania`, with "i" used as "and" in Polish)

Or at least I attempted to, given this issue.

I do the same with at least one more goal where I beemind pinging/attemptin to trigger something and similarly log successes - to encourage myself and to mark what seems to typically succeed. So far I never needed multiword hashtag there, but sooner or later I will need it.

> Yeah, I wanted to be quite restrictive about what's parsed as a hashtag to prevent false positives, like "we're #1!" or "called the doctor on their cell#" 

Are hashtags enabled or disabled by default? I thought that are disabled, so one needs to make decision to show them on their graph.

Also, is something like "must start from letter, later letters or undescores" is likely to trigger more false positives than false negatives? (maybe you have counterexample(s) in the test suite)

**Comment by dreeves** [comment] 2019-11-09 18:58
Great point that hashtags are disabled by default and so we don't need to be so paranoid about accidental hashtaggage!

Also, it turns out that not allowing underscores was an accidental regression! That's now fixed:

https://github.com/beeminder/road/commit/8d336ac39b84efd2cdd5ecc29c2e5c472d268d4f

http://beeminder.com/changelog#3193

So the remaining question is whether there's a use case for dashes specifically or if underscores are good enough. I wouldn't mind modeling this on how Twitter does it. But in the meantime my inclination is to assume it's good to be restrictive and await a specific use case for why it's too restrictive before relaxing it.

**Closed by dreeves** 2019-11-09 18:58 UTC
Labels: ADO, PEA, RFE, UVI, zap

**Comment by matkoniecz** [comment] 2019-11-09 20:30
Especially as in my case dashes were attempted only after underscores refused to work.
